export const ErrorType = {
    //TODO
    ERROR_GET_TODO: "ERROR_GET_TODO",
    ERROR_ADD_TODO: "ERROR_ADD_TODO",
    ERROR_EDIT_TODO: "ERROR_EDIT_TODO",
    ERROR_DELETE_TODO: "ERROR_DELETE_TODO",

    //USER
    ERROR_LOGIN: "ERROR_LOGIN",
    ERROR_LOGOUT: "ERROR_LOGOUT",
    ERROR_CHECK_LOGIN: "ERROR_CHECK_LOGIN",


    //CLEAN
    CLEAN_ERROR: "CLEAN_ERROR"
}